import { Injectable, signal } from '@angular/core';
import { Analysis, AnalysisType } from '../models/analysis.model';
import { MOCK_ANALYSES } from '../constants/mock-data';

@Injectable({ providedIn: 'root' })
export class AnalysisService {
  private _analyses = signal<Analysis[]>([...MOCK_ANALYSES]);
  readonly analyses = this._analyses.asReadonly();

  getAll(): Analysis[] { return this._analyses(); }

  getByType(type: AnalysisType): Analysis[] {
    return this._analyses().filter(a => a.type === type);
  }

  getById(id: string): Analysis | undefined {
    return this._analyses().find(a => a.id === id);
  }

  /** Simulate calling backend AI endpoint */
  generateAnalysis(type: AnalysisType, metrics: Analysis['metrics']): Analysis {
    const now = new Date();
    let period: string;
    let periodLabel: string;

    if (type === 'daily') {
      period = now.toISOString().split('T')[0];
      periodLabel = now.toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });
    } else if (type === 'weekly') {
      const week = Math.ceil(now.getDate() / 7);
      period = `${now.getFullYear()}-W${String(week).padStart(2,'0')}`;
      periodLabel = `Week ${week}, ${now.getFullYear()}`;
    } else {
      period = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
      periodLabel = now.toLocaleDateString('en-US', { year:'numeric', month:'long' });
    }

    const analysis: Analysis = {
      id: 'an-' + Date.now().toString(36),
      type, period, periodLabel, metrics,
      llmMessage: `**${periodLabel} — AI Generated Analysis**\n\nBased on the provided financial data, your net profit is **$${metrics.netProfit.toFixed(2)}** with a margin of ${metrics.profitMargin.toFixed(1)}%.\n\nTop performing category: **${metrics.topCategory.replace(/_/g,' ')}** generating $${metrics.topCategoryRevenue} in revenue.\n\nTotal of ${metrics.transactionCount} transactions processed with an average value of $${metrics.avgTransactionValue.toFixed(2)}.\n\n*This analysis was generated by the Quetsana Finance AI engine based on your actual transaction data.*`,
      insights: [
        `Net margin at ${metrics.profitMargin.toFixed(1)}%`,
        `${metrics.transactionCount} transactions this period`,
        `Average transaction: $${metrics.avgTransactionValue.toFixed(2)}`,
        `Top category: ${metrics.topCategory.replace(/_/g,' ')}`
      ],
      recommendations: [
        'Review top expense categories for optimization opportunities',
        'Consider expanding highest-performing income streams',
        'Monitor month-over-month growth trends'
      ],
      profitabilityScore: Math.min(100, Math.round(metrics.profitMargin * 2.5)),
      riskLevel: metrics.profitMargin > 20 ? 'low' : metrics.profitMargin > 10 ? 'medium' : 'high',
      trend: 'stable',
      trendPercentage: 0,
      createdAt: now.toISOString()
    };

    this._analyses.update(list => [analysis, ...list]);
    return analysis;
  }
}
