services:
  app:
    container_name: front-angular-crm-finance
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4200
    networks:
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - "app=finance"

networks:
  frontend:
    driver: bridge
