server {
    listen 4200;
    server_name localhost;

    # Caché de archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        alias /usr/share/nginx/html$uri;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback - permitir Angular router
    location / {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }
}
